services:
  - type: web
    name: road-pothole-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: YOLO_OFFLINE
        value: "True"
      - key: ULTRALYTICS_AUTOINSTALL
        value: "0"
      - key: ADMIN_SECRET_KEY
        value: "gcc2026"
