// Certified Municipal GIS Road Network & Defect Baseline for Chennai Corridors

export const DEFAULT_ROADS = [
  {
    road_id: "R001",
    name: "EVR Periyar Salai (Poonamallee High Rd)",
    classification: "Arterial Corridor",
    total_length_meters: 400.0,
    surface_type: "Bituminous Asphalt (BC/DBM)",
    construction_year: 2018,
    segments: [
      {
        segment_id: "R001-S001",
        road_id: "R001",
        road_name: "EVR Periyar Salai (Poonamallee High Rd)",
        start_chainage_m: 0.0,
        end_chainage_m: 100.0,
        length_m: 100.0,
        start_lat: 13.0827,
        start_lon: 80.2707,
        end_lat: 13.0815,
        end_lon: 80.2570,
        current_health_score: 92.0,
        health_grade: "Excellent",
        active_defect_count: 0,
        traffic_volume_vpd: 42000,
        last_scanned_at: new Date(Date.now() - 3600000).toISOString(),
      },
      {
        segment_id: "R001-S002",
        road_id: "R001",
        road_name: "EVR Periyar Salai (Poonamallee High Rd)",
        start_chainage_m: 100.0,
        end_chainage_m: 200.0,
        length_m: 100.0,
        start_lat: 13.0815,
        start_lon: 80.2570,
        end_lat: 13.0795,
        end_lon: 80.2440,
        current_health_score: 78.5,
        health_grade: "Good",
        active_defect_count: 1,
        traffic_volume_vpd: 45000,
        last_scanned_at: new Date(Date.now() - 1800000).toISOString(),
      },
      {
        segment_id: "R001-S003",
        road_id: "R001",
        road_name: "EVR Periyar Salai (Poonamallee High Rd)",
        start_chainage_m: 200.0,
        end_chainage_m: 300.0,
        length_m: 100.0,
        start_lat: 13.0780,
        start_lon: 80.2330,
        end_lat: 13.0765,
        end_lon: 80.2210,
        current_health_score: 47.0,
        health_grade: "Poor",
        active_defect_count: 5,
        traffic_volume_vpd: 48000,
        last_scanned_at: new Date().toISOString(),
      },
      {
        segment_id: "R001-S004",
        road_id: "R001",
        road_name: "EVR Periyar Salai (Poonamallee High Rd)",
        start_chainage_m: 300.0,
        end_chainage_m: 400.0,
        length_m: 100.0,
        start_lat: 13.0765,
        start_lon: 80.2210,
        end_lat: 13.0743,
        end_lon: 80.2108,
        current_health_score: 36.0,
        health_grade: "Critical",
        active_defect_count: 8,
        traffic_volume_vpd: 52000,
        last_scanned_at: new Date().toISOString(),
      },
    ],
  },
  {
    road_id: "R002",
    name: "Inner Ring Road (Jawaharlal Nehru Salai)",
    classification: "State Highway 2",
    total_length_meters: 200.0,
    surface_type: "Dense Graded Bituminous Asphalt",
    construction_year: 2017,
    segments: [
      {
        segment_id: "R002-S001",
        road_id: "R002",
        road_name: "Inner Ring Road (Jawaharlal Nehru Salai)",
        start_chainage_m: 0.0,
        end_chainage_m: 100.0,
        length_m: 100.0,
        start_lat: 13.1180,
        start_lon: 80.2230,
        end_lat: 13.1070,
        end_lon: 80.2105,
        current_health_score: 43.5,
        health_grade: "Poor",
        active_defect_count: 4,
        traffic_volume_vpd: 61000,
        last_scanned_at: new Date(Date.now() - 7200000).toISOString(),
      },
      {
        segment_id: "R002-S002",
        road_id: "R002",
        road_name: "Inner Ring Road (Jawaharlal Nehru Salai)",
        start_chainage_m: 100.0,
        end_chainage_m: 200.0,
        length_m: 100.0,
        start_lat: 13.1070,
        start_lon: 80.2105,
        end_lat: 13.0920,
        end_lon: 80.2030,
        current_health_score: 82.0,
        health_grade: "Good",
        active_defect_count: 1,
        traffic_volume_vpd: 58000,
        last_scanned_at: new Date(Date.now() - 10800000).toISOString(),
      },
    ],
  },
  {
    road_id: "R003",
    name: "Anna Salai (Mount Road Corridor)",
    classification: "Primary Commercial Corridor",
    total_length_meters: 200.0,
    surface_type: "Stone Mastic Asphalt (SMA)",
    construction_year: 2020,
    segments: [
      {
        segment_id: "R003-S001",
        road_id: "R003",
        road_name: "Anna Salai (Mount Road Corridor)",
        start_chainage_m: 0.0,
        end_chainage_m: 100.0,
        length_m: 100.0,
        start_lat: 13.0645,
        start_lon: 80.2540,
        end_lat: 13.0530,
        end_lon: 80.2480,
        current_health_score: 88.0,
        health_grade: "Excellent",
        active_defect_count: 0,
        traffic_volume_vpd: 65000,
        last_scanned_at: new Date().toISOString(),
      },
      {
        segment_id: "R003-S002",
        road_id: "R003",
        road_name: "Anna Salai (Mount Road Corridor)",
        start_chainage_m: 100.0,
        end_chainage_m: 200.0,
        length_m: 100.0,
        start_lat: 13.0530,
        start_lon: 80.2480,
        end_lat: 13.0410,
        end_lon: 80.2410,
        current_health_score: 64.0,
        health_grade: "Moderate",
        active_defect_count: 2,
        traffic_volume_vpd: 63000,
        last_scanned_at: new Date().toISOString(),
      },
    ],
  }
];

export const DEFAULT_SEGMENTS = DEFAULT_ROADS.flatMap((r) => r.segments);

export const DEFAULT_VEHICLES = [
  {
    vehicle_id: "MTC 46G",
    plate_number: "TN 01 N 9412",
    type: "Low-Floor City Transit Bus",
    camera: "Front 1080p HDR Dashcam (Sony IMX335)",
    edge_device: "NVIDIA Jetson Orin Nano (40 TOPS)",
    status: "Online",
    buffer_queue: 0,
    latitude: 13.0765,
    longitude: 80.2210,
    speed_kmh: 36,
    heading_deg: 268,
    current_road: "EVR Periyar Salai (Poonamallee High Rd)",
    current_segment: "R001-S004",
    last_ping: new Date().toISOString(),
  },
  {
    vehicle_id: "MTC 15G",
    plate_number: "TN 01 N 8320",
    type: "Electric Transit Bus",
    camera: "Forward Stereoscopic Pavement Camera",
    edge_device: "Raspberry Pi 5 + Hailo-8 AI Hat",
    status: "Online",
    buffer_queue: 0,
    latitude: 13.0780,
    longitude: 80.2330,
    speed_kmh: 28,
    heading_deg: 92,
    current_road: "EVR Periyar Salai (Poonamallee High Rd)",
    current_segment: "R001-S003",
    last_ping: new Date().toISOString(),
  },
  {
    vehicle_id: "MTC 21G",
    plate_number: "TN 01 AN 4421",
    type: "Standard Express Bus",
    camera: "Front Dashcam 1080p 60fps",
    edge_device: "NVIDIA Jetson Xavier NX",
    status: "Online",
    buffer_queue: 0,
    latitude: 13.1180,
    longitude: 80.2230,
    speed_kmh: 42,
    heading_deg: 185,
    current_road: "Inner Ring Road (Jawaharlal Nehru Salai)",
    current_segment: "R002-S001",
    last_ping: new Date().toISOString(),
  },
  {
    vehicle_id: "MTC 29C",
    plate_number: "TN 01 N 5110",
    type: "CNG City Bus",
    camera: "Dashcam 1080p 30fps",
    edge_device: "Intel NUC Edge Inference",
    status: "Online",
    buffer_queue: 0,
    latitude: 13.0645,
    longitude: 80.2540,
    speed_kmh: 31,
    heading_deg: 210,
    current_road: "Anna Salai (Mount Road Corridor)",
    current_segment: "R003-S001",
    last_ping: new Date().toISOString(),
  }
];

export const DEFAULT_DEFECTS = [];

