// Certified Municipal GIS Road Network & Defect Baseline for Chennai Corridors

export const DEFAULT_ROADS = [
  {
    road_id: "R001",
    name: "EVR Periyar Salai (Poonamallee High Rd)",
    classification: "Arterial Corridor",
    total_length_meters: 400.0,
    surface_type: "Bituminous Asphalt (BC/DBM)",
    construction_year: 2018,
    segments: [
      {
        segment_id: "R001-S001",
        road_id: "R001",
        road_name: "EVR Periyar Salai (Poonamallee High Rd)",
        start_chainage_m: 0.0,
        end_chainage_m: 100.0,
        length_m: 100.0,
        start_lat: 13.0827,
        start_lon: 80.2707,
        end_lat: 13.0815,
        end_lon: 80.2570,
        current_health_score: 92.0,
        health_grade: "Excellent",
        active_defect_count: 0,
        traffic_volume_vpd: 42000,
        last_scanned_at: new Date(Date.now() - 3600000).toISOString(),
      },
      {
        segment_id: "R001-S002",
        road_id: "R001",
        road_name: "EVR Periyar Salai (Poonamallee High Rd)",
        start_chainage_m: 100.0,
        end_chainage_m: 200.0,
        length_m: 100.0,
        start_lat: 13.0815,
        start_lon: 80.2570,
        end_lat: 13.0795,
        end_lon: 80.2440,
        current_health_score: 78.5,
        health_grade: "Good",
        active_defect_count: 1,
        traffic_volume_vpd: 45000,
        last_scanned_at: new Date(Date.now() - 1800000).toISOString(),
      },
      {
        segment_id: "R001-S003",
        road_id: "R001",
        road_name: "EVR Periyar Salai (Poonamallee High Rd)",
        start_chainage_m: 200.0,
        end_chainage_m: 300.0,
        length_m: 100.0,
        start_lat: 13.0780,
        start_lon: 80.2330,
        end_lat: 13.0765,
        end_lon: 80.2210,
        current_health_score: 47.0,
        health_grade: "Poor",
        active_defect_count: 5,
        traffic_volume_vpd: 48000,
        last_scanned_at: new Date().toISOString(),
      },
      {
        segment_id: "R001-S004",
        road_id: "R001",
        road_name: "EVR Periyar Salai (Poonamallee High Rd)",
        start_chainage_m: 300.0,
        end_chainage_m: 400.0,
        length_m: 100.0,
        start_lat: 13.0765,
        start_lon: 80.2210,
        end_lat: 13.0743,
        end_lon: 80.2108,
        current_health_score: 36.0,
        health_grade: "Critical",
        active_defect_count: 8,
        traffic_volume_vpd: 52000,
        last_scanned_at: new Date().toISOString(),
      },
    ],
  },
  {
    road_id: "R002",
    name: "Inner Ring Road (Jawaharlal Nehru Salai)",
    classification: "State Highway 2",
    total_length_meters: 200.0,
    surface_type: "Dense Graded Bituminous Asphalt",
    construction_year: 2017,
    segments: [
      {
        segment_id: "R002-S001",
        road_id: "R002",
        road_name: "Inner Ring Road (Jawaharlal Nehru Salai)",
        start_chainage_m: 0.0,
        end_chainage_m: 100.0,
        length_m: 100.0,
        start_lat: 13.1180,
        start_lon: 80.2230,
        end_lat: 13.1070,
        end_lon: 80.2105,
        current_health_score: 43.5,
        health_grade: "Poor",
        active_defect_count: 4,
        traffic_volume_vpd: 61000,
        last_scanned_at: new Date(Date.now() - 7200000).toISOString(),
      },
      {
        segment_id: "R002-S002",
        road_id: "R002",
        road_name: "Inner Ring Road (Jawaharlal Nehru Salai)",
        start_chainage_m: 100.0,
        end_chainage_m: 200.0,
        length_m: 100.0,
        start_lat: 13.1070,
        start_lon: 80.2105,
        end_lat: 13.0920,
        end_lon: 80.2030,
        current_health_score: 82.0,
        health_grade: "Good",
        active_defect_count: 1,
        traffic_volume_vpd: 58000,
        last_scanned_at: new Date(Date.now() - 10800000).toISOString(),
      },
    ],
  },
  {
    road_id: "R003",
    name: "Anna Salai (Mount Road Corridor)",
    classification: "Primary Commercial Corridor",
    total_length_meters: 200.0,
    surface_type: "Stone Mastic Asphalt (SMA)",
    construction_year: 2020,
    segments: [
      {
        segment_id: "R003-S001",
        road_id: "R003",
        road_name: "Anna Salai (Mount Road Corridor)",
        start_chainage_m: 0.0,
        end_chainage_m: 100.0,
        length_m: 100.0,
        start_lat: 13.0645,
        start_lon: 80.2540,
        end_lat: 13.0530,
        end_lon: 80.2480,
        current_health_score: 88.0,
        health_grade: "Excellent",
        active_defect_count: 0,
        traffic_volume_vpd: 65000,
        last_scanned_at: new Date().toISOString(),
      },
      {
        segment_id: "R003-S002",
        road_id: "R003",
        road_name: "Anna Salai (Mount Road Corridor)",
        start_chainage_m: 100.0,
        end_chainage_m: 200.0,
        length_m: 100.0,
        start_lat: 13.0530,
        start_lon: 80.2480,
        end_lat: 13.0410,
        end_lon: 80.2410,
        current_health_score: 64.0,
        health_grade: "Moderate",
        active_defect_count: 2,
        traffic_volume_vpd: 63000,
        last_scanned_at: new Date().toISOString(),
      },
    ],
  }
];

export const DEFAULT_SEGMENTS = DEFAULT_ROADS.flatMap((r) => r.segments);

export const DEFAULT_VEHICLES = [
  {
    vehicle_id: "MTC 46G",
    plate_number: "TN 01 N 9412",
    type: "Low-Floor City Transit Bus",
    camera: "Front 1080p HDR Dashcam (Sony IMX335)",
    edge_device: "NVIDIA Jetson Orin Nano (40 TOPS)",
    status: "Online",
    buffer_queue: 0,
    latitude: 13.0765,
    longitude: 80.2210,
    speed_kmh: 36,
    heading_deg: 268,
    current_road: "EVR Periyar Salai (Poonamallee High Rd)",
    current_segment: "R001-S004",
    last_ping: new Date().toISOString(),
  },
  {
    vehicle_id: "MTC 15G",
    plate_number: "TN 01 N 8320",
    type: "Electric Transit Bus",
    camera: "Forward Stereoscopic Pavement Camera",
    edge_device: "Raspberry Pi 5 + Hailo-8 AI Hat",
    status: "Online",
    buffer_queue: 0,
    latitude: 13.0780,
    longitude: 80.2330,
    speed_kmh: 28,
    heading_deg: 92,
    current_road: "EVR Periyar Salai (Poonamallee High Rd)",
    current_segment: "R001-S003",
    last_ping: new Date().toISOString(),
  },
  {
    vehicle_id: "MTC 21G",
    plate_number: "TN 01 AN 4421",
    type: "Standard Express Bus",
    camera: "Front Dashcam 1080p 60fps",
    edge_device: "NVIDIA Jetson Xavier NX",
    status: "Online",
    buffer_queue: 0,
    latitude: 13.1180,
    longitude: 80.2230,
    speed_kmh: 42,
    heading_deg: 185,
    current_road: "Inner Ring Road (Jawaharlal Nehru Salai)",
    current_segment: "R002-S001",
    last_ping: new Date().toISOString(),
  },
  {
    vehicle_id: "MTC 29C",
    plate_number: "TN 01 N 5110",
    type: "CNG City Bus",
    camera: "Dashcam 1080p 30fps",
    edge_device: "Intel NUC Edge Inference",
    status: "Online",
    buffer_queue: 0,
    latitude: 13.0645,
    longitude: 80.2540,
    speed_kmh: 31,
    heading_deg: 210,
    current_road: "Anna Salai (Mount Road Corridor)",
    current_segment: "R003-S001",
    last_ping: new Date().toISOString(),
  }
];

export const DEFAULT_DEFECTS = [
  {
    id: 1,
    detection_id: "DET-2026-001",
    defect_type: "pothole",
    class_name: "pothole",
    latitude: 13.118,
    longitude: 80.223,
    severity: "High",
    confidence: 0.867,
    road_id: "R002",
    road_name: "Inner Ring Road (Jawaharlal Nehru Salai)",
    segment_id: "R002-S001",
    exact_chainage_m: 24.5,
    bus_count: 2,
    bus_ids: "MTC 46G, MTC 21G",
    reporting_vehicles: ["MTC 46G", "MTC 21G"],
    total_detections: 14,
    is_multi_bus_verified: true,
    bbox: {
      x_min: 210,
      y_min: 160,
      x_max: 290,
      y_max: 215,
      pixel_area: 4400,
      estimated_physical_width_cm: 48.0,
      estimated_physical_length_cm: 36.5,
    },
    first_detected: new Date(Date.now() - 7200000).toISOString(),
    last_detected: new Date(Date.now() - 300000).toISOString(),
    model_version: "YOLOv8-road-v1",
    status: "Verified",
    source: "transit_bus"
  },
  {
    id: 2,
    detection_id: "DET-2026-002",
    defect_type: "alligator_crack",
    class_name: "alligator_crack",
    latitude: 13.078,
    longitude: 80.233,
    severity: "Critical",
    confidence: 0.893,
    road_id: "R001",
    road_name: "EVR Periyar Salai (Poonamallee High Rd)",
    segment_id: "R001-S003",
    exact_chainage_m: 212.0,
    bus_count: 2,
    bus_ids: "MTC 15G, MTC 46G",
    reporting_vehicles: ["MTC 15G", "MTC 46G"],
    total_detections: 19,
    is_multi_bus_verified: true,
    bbox: {
      x_min: 140,
      y_min: 140,
      x_max: 240,
      y_max: 220,
      pixel_area: 8000,
      estimated_physical_width_cm: 76.0,
      estimated_physical_length_cm: 64.0,
    },
    first_detected: new Date(Date.now() - 5400000).toISOString(),
    last_detected: new Date(Date.now() - 120000).toISOString(),
    model_version: "YOLOv8-road-v1",
    status: "Open",
    source: "transit_bus"
  },
  {
    id: 3,
    detection_id: "DET-2026-003",
    defect_type: "waterlogging",
    class_name: "waterlogging",
    latitude: 13.0765,
    longitude: 80.221,
    severity: "High",
    confidence: 0.847,
    road_id: "R001",
    road_name: "EVR Periyar Salai (Poonamallee High Rd)",
    segment_id: "R001-S004",
    exact_chainage_m: 310.0,
    bus_count: 1,
    bus_ids: "MTC 46G",
    reporting_vehicles: ["MTC 46G"],
    total_detections: 8,
    is_multi_bus_verified: false,
    bbox: {
      x_min: 100,
      y_min: 180,
      x_max: 360,
      y_max: 245,
      pixel_area: 16900,
      estimated_physical_width_cm: 155.0,
      estimated_physical_length_cm: 85.0,
    },
    first_detected: new Date(Date.now() - 3600000).toISOString(),
    last_detected: new Date(Date.now() - 600000).toISOString(),
    model_version: "YOLOv8-road-v1",
    status: "Open",
    source: "transit_bus"
  },
  {
    id: 4,
    detection_id: "DET-2026-004",
    defect_type: "longitudinal_crack",
    class_name: "longitudinal_crack",
    latitude: 13.0743,
    longitude: 80.2108,
    severity: "Medium",
    confidence: 0.812,
    road_id: "R001",
    road_name: "EVR Periyar Salai (Poonamallee High Rd)",
    segment_id: "R001-S004",
    exact_chainage_m: 385.0,
    bus_count: 2,
    bus_ids: "MTC 46G, MTC 15G",
    reporting_vehicles: ["MTC 46G", "MTC 15G"],
    total_detections: 12,
    is_multi_bus_verified: true,
    bbox: {
      x_min: 240,
      y_min: 150,
      x_max: 290,
      y_max: 260,
      pixel_area: 5500,
      estimated_physical_width_cm: 18.0,
      estimated_physical_length_cm: 120.0,
    },
    first_detected: new Date(Date.now() - 2400000).toISOString(),
    last_detected: new Date(Date.now() - 450000).toISOString(),
    model_version: "YOLOv8-road-v1",
    status: "Verified",
    source: "transit_bus"
  }
];
